name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement, triage]
assignees:
body:
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe the desired feature
    validations:
      required: true
  - type: textarea
    id: example-feature
    attributes:
      label: Give an example of how this feature would be used
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
